// client-next/src/components/layout/Main.tsx
"use client";

import type { ReactNode } from "react";
import Sidebar from "./Sidebar";

interface MainProps {
    children: ReactNode;
}

export default function Main({ children }: MainProps) {
    return (
        <div className="flex h-full w-full bg-notion-canvas">
            <div className="flex-shrink-0 h-full">
                <Sidebar />
            </div>
            <main className="flex-1 flex flex-col h-full bg-notion-canvas overflow-hidden relative">
                {children}
            </main>
        </div>
    );
}

// client/src/lib/ui/Layout/Main.svelte
<script lang="ts">
    import type { Snippet } from "svelte";
    import Sidebar from "./Main/Sidebar.svelte";

    interface Props {
        children: Snippet;
    }

    let { children }: Props = $props();
</script>

<div class="flex h-full w-full">
    <Sidebar />
    <main class="flex-1 flex flex-col h-full bg-white dark:bg-[#121212] overflow-hidden relative">
        {@render children()}
    </main>
</div>
