// client-next/src/components/views/Network.tsx
"use client";

import { useEffect, useMemo, useState } from "react";
import { useSharedStore } from "@/lib/stores/shared";
import { useNostrIdentity } from "@/lib/nostr/identity";
import { showToast } from "@/lib/stores/ui";
import "./network.css";

interface RelayRow {
    url: string;
    connected: boolean;
    last_error: string | null;
}

interface PeerRow {
    status: "up" | "down";
    name: string;
    addr: string;
    meta: string;
}

export default function Network() {
    const [bootstrapInput, setBootstrapInput] = useState("");
    const [relays, setRelays] = useState<RelayRow[]>([]);
    const [isLoadingRelays, setIsLoadingRelays] = useState(false);

    const { npub, publicId } = useNostrIdentity();
    const accounts = useSharedStore((s) => s.accounts);
    const failedAccounts = useSharedStore((s) => s.failedAccounts);
    const server = useSharedStore((s) => s.server);

    const nodeId = useMemo(
        () => npub || publicId || "no identity on this account",
        [npub, publicId],
    );

    const peers = useMemo(() => {
        const rows: PeerRow[] = accounts.map((account) => ({
            status: "up",
            name: account.fullname || account.email_address,
            addr: account.email_address,
            meta: "server reachable",
        }));
        failedAccounts.forEach((account) => {
            rows.push({
                status: "down",
                name: account.fullname || account.email_address,
                addr: account.email_address,
                meta: "unreachable",
            });
        });
        return rows;
    }, [accounts, failedAccounts]);

    const downCount = useMemo(
        () => peers.filter((p) => p.status === "down").length,
        [peers],
    );
    const relaysConnected = useMemo(
        () => relays.filter((r) => r.connected).length,
        [relays],
    );

    useEffect(() => {
        let cancelled = false;
        const fetchRelays = async () => {
            setIsLoadingRelays(true);
            try {
                const res = await fetch(`${server}/nostr/relays`);
                const json = await res.json();
                if (cancelled) return;
                if (json.success && Array.isArray(json.data)) {
                    setRelays(json.data);
                }
            } catch {
                if (cancelled) return;
                setRelays([]);
            } finally {
                if (!cancelled) setIsLoadingRelays(false);
            }
        };
        fetchRelays();
        return () => {
            cancelled = true;
        };
    }, [server]);

    const copyNodeId = async () => {
        try {
            await navigator.clipboard.writeText(nodeId);
            showToast({ content: "node id copied" });
        } catch {
            /* clipboard unavailable — ignore */
        }
    };

    const addBootstrap = () => {
        const value = bootstrapInput.trim();
        if (!value) return;
        showToast({
            content: "bootstrap peers need the node API — not wired yet",
        });
        setBootstrapInput("");
    };

    const relayName = (url: string): string => {
        try {
            return new URL(url).hostname;
        } catch {
            return url;
        }
    };

    return (
        <div className="settings-panel active">
            <div className="settings-title">Node network</div>
            <div className="settings-sub">Who your node is talking to right now.</div>

            <div className="settings-section">
                <h3>Your node</h3>
                <div className="settings-node-id">
                    <span>{nodeId}</span>
                    <button onClick={copyNodeId} title="Copy" aria-label="Copy node id">
                        <svg viewBox="0 0 24 24"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
                    </button>
                </div>
                <div className="settings-row">
                    <div>
                        <div className="settings-row-label">Status</div>
                        <div className="settings-row-desc">Connected to Nostr relays for decentralized mail delivery.</div>
                    </div>
                    <div className="tag">
                        <span className={"status-dot " + (relaysConnected > 0 ? "up" : "down")}></span>
                        {relaysConnected > 0 ? `${relaysConnected} relay${relaysConnected !== 1 ? "s" : ""}` : "offline"}
                    </div>
                </div>
            </div>

            <div className="settings-section">
                <h3>Network health</h3>
                <div className="stat-row">
                    <div className="stat"><span className="stat-num">{relays.length}</span><span className="stat-label">relays configured</span></div>
                    <div className="stat"><span className="stat-num">{relaysConnected}</span><span className="stat-label">connected</span></div>
                    <div className="stat"><span className="stat-num">{peers.length}</span><span className="stat-label">accounts</span></div>
                    <div className="stat"><span className="stat-num">{downCount}</span><span className="stat-label">failed</span></div>
                </div>
            </div>

            <div className="settings-section">
                <h3>Nostr relays</h3>
                {isLoadingRelays ? (
                    <div className="empty-note">Loading relay status…</div>
                ) : relays.length === 0 ? (
                    <div className="empty-note">No relays configured. Register a Nostr identity to connect.</div>
                ) : (
                    <div className="peer-list">
                        {relays.map((relay, index) => (
                            <div className="peer-row" key={`${relay.url}-${index}`}>
                                <span className={"status-dot " + (relay.connected ? "up" : "down")}></span>
                                <div className="peer-main">
                                    <div className="peer-name">{relayName(relay.url)}</div>
                                    <div className="peer-addr">{relay.url}</div>
                                </div>
                                <div className="peer-meta">
                                    {relay.connected
                                        ? "connected"
                                        : relay.last_error
                                            ? relay.last_error
                                            : "disconnected"}
                                </div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            <div className="settings-section">
                <h3>Connected accounts</h3>
                {peers.length === 0 ? (
                    <div className="empty-note">No accounts yet.</div>
                ) : (
                    <div className="peer-list">
                        {peers.map((peer, index) => (
                            <div className="peer-row" key={`${peer.addr}-${index}`}>
                                <span className={"status-dot " + (peer.status === "up" ? "up" : "down")}></span>
                                <div className="peer-main">
                                    <div className="peer-name">{peer.name}</div>
                                    <div className="peer-addr">{peer.addr}</div>
                                </div>
                                <div className="peer-meta">{peer.meta}</div>
                            </div>
                        ))}
                    </div>
                )}
            </div>

            <div className="settings-section">
                <h3>Bootstrap peers</h3>
                <div className="settings-row-desc" style={{ marginBottom: "4px" }}>Add a known peer address to help your node find the rest of the network.</div>
                <div className="add-row">
                    <input
                        type="text"
                        value={bootstrapInput}
                        onChange={(e) => setBootstrapInput(e.target.value)}
                        placeholder="node1… or host:port"
                        onKeyDown={(e) => {
                            if (e.key === "Enter") addBootstrap();
                        }}
                    />
                    <button className="settings-btn" onClick={addBootstrap}>Add</button>
                </div>
            </div>
        </div>
    );
}

// client/src/lib/ui/Layout/Main/Views/Network.svelte
<script lang="ts">
    import { SharedStore } from "$lib/stores/shared.svelte";
    import { nostrIdentity } from "$lib/nostr/identity.svelte";
    import { show as showToast } from "$lib/ui/Components/Toast";
    import { onMount } from "svelte";
    import type { Account } from "$lib/types";

    interface RelayRow {
        url: string;
        connected: boolean;
        last_error: string | null;
    }

    interface PeerRow {
        status: "up" | "down";
        name: string;
        addr: string;
        meta: string;
    }

    let bootstrapInput = $state("");
    let relays: RelayRow[] = $state([]);
    let isLoadingRelays = $state(false);

    let nodeId = $derived(
        nostrIdentity.state.npub ||
        nostrIdentity.state.publicId ||
        "no identity on this account",
    );

    let accounts = $derived(SharedStore.accounts);

    let peers = $derived.by(() => {
        const rows: PeerRow[] = accounts.map((account) => ({
            status: "up",
            name: account.fullname || account.email_address,
            addr: account.email_address,
            meta: "server reachable",
        }));
        SharedStore.failedAccounts.forEach((account) => {
            rows.push({
                status: "down",
                name: account.fullname || account.email_address,
                addr: account.email_address,
                meta: "unreachable",
            });
        });
        return rows;
    });

    let upCount = $derived(peers.filter((p) => p.status === "up").length);
    let downCount = $derived(peers.filter((p) => p.status === "down").length);
    let relaysConnected = $derived(relays.filter((r) => r.connected).length);

    async function fetchRelays() {
        isLoadingRelays = true;
        try {
            const res = await fetch(`${SharedStore.server}/nostr/relays`);
            const json = await res.json();
            if (json.success && Array.isArray(json.data)) {
                relays = json.data;
            }
        } catch {
            relays = [];
        } finally {
            isLoadingRelays = false;
        }
    }

    onMount(() => {
        fetchRelays();
    });

    async function copyNodeId() {
        try {
            await navigator.clipboard.writeText(nodeId);
            showToast({ content: "node id copied" });
        } catch {
            /* clipboard unavailable — ignore */
        }
    }

    function addBootstrap() {
        const value = bootstrapInput.trim();
        if (!value) return;
        showToast({
            content: "bootstrap peers need the node API — not wired yet",
        });
        bootstrapInput = "";
    }

    function relayName(url: string): string {
        try {
            return new URL(url).hostname;
        } catch {
            return url;
        }
    }
</script>

<div class="settings-panel active">
    <div class="settings-title">Node network</div>
    <div class="settings-sub">Who your node is talking to right now.</div>

    <div class="settings-section">
        <h3>Your node</h3>
        <div class="settings-node-id">
            <span>{nodeId}</span>
            <button onclick={copyNodeId} title="Copy" aria-label="Copy node id">
                <svg viewBox="0 0 24 24"><rect x="9" y="9" width="12" height="12" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
            </button>
        </div>
        <div class="settings-row">
            <div>
                <div class="settings-row-label">Status</div>
                <div class="settings-row-desc">Connected to Nostr relays for decentralized mail delivery.</div>
            </div>
            <div class="tag">
                <span class="status-dot" class:up={relaysConnected > 0} class:down={relaysConnected === 0}></span>
                {relaysConnected > 0 ? `${relaysConnected} relay${relaysConnected !== 1 ? "s" : ""}` : "offline"}
            </div>
        </div>
    </div>

    <div class="settings-section">
        <h3>Network health</h3>
        <div class="stat-row">
            <div class="stat"><span class="stat-num">{relays.length}</span><span class="stat-label">relays configured</span></div>
            <div class="stat"><span class="stat-num">{relaysConnected}</span><span class="stat-label">connected</span></div>
            <div class="stat"><span class="stat-num">{peers.length}</span><span class="stat-label">accounts</span></div>
            <div class="stat"><span class="stat-num">{downCount}</span><span class="stat-label">failed</span></div>
        </div>
    </div>

    <div class="settings-section">
        <h3>Nostr relays</h3>
        {#if isLoadingRelays}
            <div class="empty-note">Loading relay status…</div>
        {:else if relays.length === 0}
            <div class="empty-note">No relays configured. Register a Nostr identity to connect.</div>
        {:else}
            <div class="peer-list">
                {#each relays as relay}
                    <div class="peer-row">
                        <span class="status-dot" class:up={relay.connected} class:down={!relay.connected}></span>
                        <div class="peer-main">
                            <div class="peer-name">{relayName(relay.url)}</div>
                            <div class="peer-addr">{relay.url}</div>
                        </div>
                        <div class="peer-meta">
                            {#if relay.connected}
                                connected
                            {:else if relay.last_error}
                                {relay.last_error}
                            {:else}
                                disconnected
                            {/if}
                        </div>
                    </div>
                {/each}
            </div>
        {/if}
    </div>

    <div class="settings-section">
        <h3>Connected accounts</h3>
        {#if peers.length === 0}
            <div class="empty-note">No accounts yet.</div>
        {:else}
            <div class="peer-list">
                {#each peers as peer}
                    <div class="peer-row">
                        <span class="status-dot" class:up={peer.status === "up"} class:down={peer.status === "down"}></span>
                        <div class="peer-main">
                            <div class="peer-name">{peer.name}</div>
                            <div class="peer-addr">{peer.addr}</div>
                        </div>
                        <div class="peer-meta">{peer.meta}</div>
                    </div>
                {/each}
            </div>
        {/if}
    </div>

    <div class="settings-section">
        <h3>Bootstrap peers</h3>
        <div class="settings-row-desc" style="margin-bottom:4px;">Add a known peer address to help your node find the rest of the network.</div>
        <div class="add-row">
            <input
                type="text"
                bind:value={bootstrapInput}
                placeholder="node1… or host:port"
                onkeydown={(e) => e.key === "Enter" && addBootstrap()}
            />
            <button class="settings-btn" onclick={addBootstrap}>Add</button>
        </div>
    </div>
</div>

<style>
    :global {
        .settings-panel {
            flex-grow: 1;
            display: none;
            flex-direction: column;
            background: var(--cream);
            padding: 32px 44px;
            overflow-y: auto;
            min-width: 0;
        }

        .settings-panel.active {
            display: flex;
        }

        .settings-panel .settings-title {
            font-family: var(--ui);
            font-size: 1.5rem;
            font-weight: 600;
            margin-bottom: 6px;
        }

        .settings-panel .settings-sub {
            font-size: 0.82rem;
            color: var(--ink-faint);
            margin-bottom: 34px;
        }

        .settings-panel .settings-section {
            max-width: 560px;
            margin-bottom: 34px;
            padding-bottom: 34px;
            border-bottom: 1px solid var(--glass-border);
        }

        .settings-panel .settings-section:last-of-type {
            border-bottom: none;
        }

        .settings-panel .settings-section h3 {
            font-family: var(--ui);
            font-size: 0.68rem;
            font-weight: 600;
            color: var(--ink-faint);
            text-transform: uppercase;
            letter-spacing: 0.04em;
            margin-bottom: 16px;
        }

        .settings-panel .settings-row {
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 16px;
            padding: 12px 0;
        }

        .settings-panel .settings-row-label {
            font-size: 0.86rem;
            color: var(--ink);
            font-weight: 500;
        }

        .settings-panel .settings-row-desc {
            font-size: 0.74rem;
            color: var(--ink-faint);
            margin-top: 2px;
        }

        .settings-panel .settings-node-id {
            font-family: var(--ui);
            font-size: 0.78rem;
            color: var(--ink-dim);
            background: var(--glass-strong);
            border: 1px solid var(--glass-border);
            border-radius: var(--radius-sm);
            padding: 11px 14px;
            word-break: break-all;
            display: flex;
            align-items: center;
            justify-content: space-between;
            gap: 10px;
        }

        .settings-panel .settings-node-id button {
            color: var(--ink-faint);
            flex-shrink: 0;
        }

        .settings-panel .settings-node-id button:hover {
            color: var(--accent);
        }

        .settings-panel .settings-node-id button svg {
            width: 15px;
            height: 15px;
            stroke: currentColor;
            fill: none;
            stroke-width: 1.9;
            stroke-linecap: round;
            stroke-linejoin: round;
        }

        .settings-panel .tag {
            background: var(--glass-strong);
            border: 1px solid var(--glass-border);
            color: var(--ink-dim);
            padding: 6px 12px;
            border-radius: var(--radius-sm);
            font-size: 0.72rem;
            font-weight: 600;
            display: flex;
            align-items: center;
            gap: 7px;
            font-family: var(--ui);
        }

        .settings-panel .stat-row {
            display: flex;
            gap: 28px;
            flex-wrap: wrap;
            margin-bottom: 6px;
        }

        .settings-panel .stat {
            display: flex;
            flex-direction: column;
            gap: 2px;
        }

        .settings-panel .stat .stat-num {
            font-family: var(--ui);
            font-size: 1.5rem;
            font-weight: 600;
            color: var(--ink);
        }

        .settings-panel .stat .stat-label {
            font-size: 0.68rem;
            color: var(--ink-faint);
        }

        .settings-panel .status-dot {
            width: 8px;
            height: 8px;
            border-radius: 50%;
            flex-shrink: 0;
        }

        .settings-panel .status-dot.up { background: var(--direct); }
        .settings-panel .status-dot.degraded { background: var(--relay); }
        .settings-panel .status-dot.down { background: var(--ink-faint); }

        .settings-panel .peer-row {
            display: flex;
            align-items: center;
            gap: 14px;
            padding: 12px 0;
            border-bottom: 1px solid var(--glass-border);
        }

        .settings-panel .peer-row:last-child {
            border-bottom: none;
        }

        .settings-panel .peer-main {
            flex: 1;
            min-width: 0;
        }

        .settings-panel .peer-name {
            font-size: 0.86rem;
            font-weight: 600;
            color: var(--ink);
        }

        .settings-panel .peer-addr {
            font-size: 0.72rem;
            color: var(--ink-faint);
            font-family: var(--ui);
            word-break: break-all;
        }

        .settings-panel .peer-meta {
            font-size: 0.7rem;
            color: var(--ink-faint);
            white-space: nowrap;
            text-align: right;
        }

        .settings-panel .empty-note {
            padding: 24px 0;
            color: var(--ink-faint);
            font-size: 0.82rem;
        }

        .settings-panel .stub-note {
            font-size: 0.7rem;
            color: var(--ink-faint);
            margin-top: 10px;
            max-width: 52ch;
        }

        .settings-panel .add-row {
            display: flex;
            gap: 10px;
            margin-top: 16px;
        }

        .settings-panel .add-row input {
            flex: 1;
            background: var(--glass-strong);
            border: 1px solid var(--glass-border);
            border-radius: 100px;
            padding: 9px 16px;
            font-size: 0.82rem;
            color: var(--ink);
            outline: none;
            font-family: var(--body);
        }

        .settings-panel .add-row input::placeholder {
            color: var(--ink-faint);
        }

        .settings-panel .settings-btn {
            font-family: var(--ui);
            font-size: 0.8rem;
            font-weight: 600;
            color: var(--ink);
            background: var(--glass-strong);
            border: 1px solid var(--glass-border);
            padding: 9px 18px;
            border-radius: 100px;
            transition: background 0.15s ease, transform 0.15s ease;
        }

        .settings-panel .settings-btn:hover {
            background: var(--glass-solid);
            transform: translateY(-1px);
        }
    }
</style>
